name = "sjtuaa-backend"
main = "src/index.js"
compatibility_date = "2024-03-27"

[[d1_databases]]
binding = "DB"
database_name = "sjtuaa-db"
database_id = "3dd50307-3834-4552-8806-7af21a1ad629"

[[r2_buckets]]
binding = "IMAGES_BUCKET"
bucket_name = "sjtuaa-images"

# We execute build steps explicitly in GitHub Actions / Makefile rather than here.
